### PR TITLE
Feature/logger

### PR DESCRIPTION
**Pull request by ilija-savic-devtech**
# What's the purpose of this MR?
Logger
# Impact Analysis
(N/A)
# Where should the tester start?
- In application folder logs you can see all activity of our app
# How should this be manually tested?
(N/A)
# Any background context you want to provide?
(N/A)
# What are the relevant tickets?
(N/A)
# Screenshots (if appropriate)
(N/A)

### CODE REVIEW

**Comment by ilija-savic-devtech** [comment]
This is what i done yesterday, is this good approach?

**Comment by goran-erhartic-devtech** [comment]
How about you try using dependency injection for the logger instead of globals? :)

**Comment by ilija-savic-devtech** [comment]
I added logger as dependency injection in services. In class DbConnection i don't see any other way of using Logger instead as a global variable because this class is singleton... or there is?

**Comment by goran-erhartic-devtech** [comment]
sure there is ;) try to figure it out on your own, and if you get stuck, as always, I will point you in the right direction

**Comment by goran-erhartic-devtech** [comment]
try passing $logger to DbConnection class's methods instead of it's constructor

**Comment by ilija-savic-devtech** [comment]
Like this?

**Comment by goran-erhartic-devtech** [comment]
that's right! 👍 
cool, now what I would like you to do is to reorganize the folder structure in your code (we should have done this earlier). I will merge this to develop, please create a new feature from it and I will come to you to explain further

**Pull request merged**
